import {defineArrayMember, defineField, defineType} from 'sanity'

export default defineType({
  name: 'article',
  title: 'Article & Guide',
  type: 'document',
  groups: [
    {name: 'content', title: 'Content', default: true},
    {name: 'context', title: 'Planning Context'},
    {name: 'publishing', title: 'Publishing'},
    {name: 'seo', title: 'Search & Sharing'},
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      group: 'content',
      validation: (Rule) => Rule.required().max(120),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      group: 'publishing',
      options: {source: 'title', maxLength: 96},
      validation: (Rule) => Rule.required(),
    }),
    defineField({name: 'heroImage', title: 'Hero Image', type: 'contentImage', group: 'content'}),
    defineField({
      name: 'excerpt',
      title: 'Excerpt',
      type: 'text',
      rows: 3,
      group: 'content',
      description: 'Used on guide cards and as the default search description.',
      validation: (Rule) => Rule.required().max(300).warning('Add a concise excerpt before promoting this guide.'),
    }),
    defineField({
      name: 'body',
      title: 'Body',
      type: 'richText',
      group: 'content',
      validation: (Rule) => Rule.required().min(1).warning('The guide needs body content before delivery.'),
    }),
    defineField({
      name: 'category',
      title: 'Category',
      type: 'string',
      group: 'context',
      options: {
        list: [
          {title: 'Travel Guide', value: 'travel_guide'},
          {title: 'Island Deep-Dive', value: 'island_deep_dive'},
          {title: 'Food & Dining', value: 'food_dining'},
          {title: 'Adventure', value: 'adventure'},
          {title: 'Culture', value: 'culture'},
          {title: 'Insider Tips', value: 'insider_tips'},
          {title: 'Cruise Planning', value: 'cruise_planning'},
          {title: 'Planning Basics', value: 'planning_basics'},
          {title: 'Events & Seasons', value: 'events_seasons'},
        ],
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'relatedDestination',
      title: 'Related Destination',
      type: 'reference',
      group: 'context',
      to: [{type: 'destination'}],
    }),
    defineField({name: 'author', title: 'Author', type: 'reference', group: 'publishing', to: [{type: 'author'}]}),
    defineField({
      name: 'readTimeMinutes',
      title: 'Read Time (minutes)',
      type: 'number',
      group: 'publishing',
      validation: (Rule) => Rule.required().min(1).max(90).integer().warning('Add the estimated read time shown on cards.'),
    }),
    defineField({
      name: 'buddyPrompt',
      title: 'Ask Buddy Prompt',
      type: 'text',
      rows: 3,
      group: 'context',
      description: 'Optional hand-tuned prompt used by “Ask Buddy” actions.',
      validation: (Rule) => Rule.max(500),
    }),
    defineField({
      name: 'planningSummary',
      title: 'Planning Summary',
      type: 'text',
      rows: 4,
      group: 'context',
      description: 'Concise facts Buddy may use as planning context. Do not put live prices or availability here.',
      validation: (Rule) => Rule.max(1000),
    }),
    defineField({
      name: 'evidenceSources',
      title: 'Editorial Evidence Sources',
      type: 'array',
      group: 'context',
      description: 'Reviewed repository sources supporting this article. References do not replace claim-level links in the body.',
      of: [defineArrayMember({type: 'reference', to: [{type: 'researchSource'}]})],
    }),
    defineField({
      name: 'editorialReviewStatus',
      title: 'Editorial Evidence Status',
      type: 'string',
      group: 'context',
      options: {list: [
        {title: 'Legacy — not evidence reviewed', value: 'legacy_unreviewed'},
        {title: 'Researching', value: 'researching'},
        {title: 'Ready for editorial review', value: 'ready_for_review'},
        {title: 'Blocked', value: 'blocked'},
        {title: 'Approved', value: 'approved'},
      ]},
    }),
    defineField({
      name: 'editorialReviewNotes',
      title: 'Editorial Evidence Notes',
      type: 'text',
      rows: 5,
      group: 'context',
      validation: (Rule) => Rule.max(1600),
    }),
    defineField({
      name: 'channels',
      title: 'Delivery Channels',
      type: 'array',
      group: 'publishing',
      of: [defineArrayMember({type: 'string'})],
      options: {list: [{title: 'Web', value: 'web'}, {title: 'Mobile', value: 'mobile'}, {title: 'Buddy planning context', value: 'buddy'}]},
      initialValue: ['web', 'mobile'],
      validation: (Rule) => Rule.required().min(1),
    }),
    defineField({name: 'publishedAt', title: 'Published At', type: 'datetime', group: 'publishing', initialValue: () => new Date().toISOString()}),
    defineField({name: 'reviewedAt', title: 'Last Reviewed', type: 'date', group: 'publishing'}),
    defineField({name: 'featured', title: 'Featured', type: 'boolean', group: 'publishing', initialValue: false}),
    defineField({name: 'order', title: 'Display Order', type: 'number', group: 'publishing', initialValue: 99}),
    defineField({name: 'source', title: 'Imported Source', type: 'contentSource', group: 'publishing'}),
    defineField({
      name: 'tags',
      title: 'Tags',
      type: 'array',
      group: 'context',
      of: [defineArrayMember({type: 'string'})],
      options: {layout: 'tags'},
    }),
    defineField({name: 'seo', title: 'Search & Sharing', type: 'seo', group: 'seo'}),
  ],
  preview: {
    select: {title: 'title', media: 'heroImage', category: 'category', destination: 'relatedDestination.name'},
    prepare({title, media, category, destination}) {
      return {title: title || 'Untitled guide', subtitle: [category?.replace(/_/g, ' '), destination].filter(Boolean).join(' · '), media}
    },
  },
  orderings: [
    {title: 'Newest first', name: 'publishedDesc', by: [{field: 'publishedAt', direction: 'desc'}]},
    {title: 'Featured and manual order', name: 'featuredOrder', by: [{field: 'featured', direction: 'desc'}, {field: 'order', direction: 'asc'}]},
  ],
})
