import {defineArrayMember, defineField, defineType} from 'sanity'

/** Review-only proposal for an official place identity absent from Supabase. */
export default defineType({
  name: 'canonicalPlaceCandidate',
  title: 'Missing Canonical Place Candidate',
  type: 'document',
  description: 'Evidence for a possible future Supabase place. Publishing this document does not create, activate, locate, or deliver a place.',
  groups: [
    {name: 'identity', title: 'Identity', default: true},
    {name: 'location', title: 'Location Evidence'},
    {name: 'readiness', title: 'Traveler Readiness'},
    {name: 'review', title: 'Canonical Review'},
  ],
  fields: [
    defineField({name: 'title', title: 'Candidate Name', type: 'string', group: 'identity', validation: (Rule) => Rule.required().max(180)}),
    defineField({name: 'slug', title: 'Candidate Slug', type: 'slug', group: 'identity', options: {source: 'title', maxLength: 96}, validation: (Rule) => Rule.required()}),
    defineField({name: 'destination', title: 'Destination', type: 'reference', group: 'identity', to: [{type: 'destination'}], validation: (Rule) => Rule.required()}),
    defineField({name: 'islandName', title: 'Island Name', type: 'string', group: 'identity', validation: (Rule) => Rule.required().max(120)}),
    defineField({name: 'officialSourceName', title: 'Official Source Name', type: 'string', group: 'identity', validation: (Rule) => Rule.required().max(180)}),
    defineField({
      name: 'featureType',
      title: 'Proposed Feature Type',
      type: 'string',
      group: 'identity',
      options: {list: [
        {title: 'Community or settlement', value: 'community'},
        {title: 'Geographic area', value: 'geographic_area'},
        {title: 'Protected area', value: 'protected_area'},
        {title: 'Beach', value: 'beach'},
        {title: 'Natural feature', value: 'natural_feature'},
        {title: 'Historic site', value: 'historic_site'},
        {title: 'Cultural site', value: 'cultural_site'},
        {title: 'Museum', value: 'museum'},
        {title: 'Lighthouse', value: 'lighthouse'},
        {title: 'Marketplace', value: 'marketplace'},
        {title: 'Shipwreck', value: 'shipwreck'},
        {title: 'Research centre', value: 'research_center'},
        {title: 'Agricultural identity', value: 'agricultural_area'},
        {title: 'Accommodation property', value: 'accommodation_property'},
        {title: 'Activity operator or guide', value: 'activity_operator'},
        {title: 'Multiple or distributed sites', value: 'multi_site_identity'},
      ]},
      validation: (Rule) => Rule.required(),
    }),
    defineField({name: 'categoryProposal', title: 'Proposed Supabase Category', type: 'string', group: 'identity', description: 'A review hint only; it is not a catalog write.', validation: (Rule) => Rule.required().max(100)}),
    defineField({name: 'identityEvidence', title: 'Official Identity Evidence', type: 'array', group: 'identity', of: [defineArrayMember({type: 'reference', to: [{type: 'researchSource'}]})], validation: (Rule) => Rule.required().min(1)}),
    defineField({name: 'identityBoundary', title: 'Identity Boundary', type: 'text', rows: 4, group: 'identity', description: 'Explains whether the identity is one feature, a community, an area, a related visitor site, or multiple sites.', validation: (Rule) => Rule.required().max(1400)}),
    defineField({name: 'locationReview', title: 'Official Location Evidence', type: 'placeLocationReview', group: 'location', validation: (Rule) => Rule.required()}),
    defineField({name: 'travelerReadinessReview', title: 'Traveler Readiness Evidence', type: 'placeTravelerReadinessReview', group: 'readiness'}),
    defineField({name: 'contentReadinessReview', title: 'Accessibility, Copy & Media Evidence', type: 'placeContentReadinessReview', group: 'readiness'}),
    defineField({
      name: 'rejectedSupabaseMatches',
      title: 'Rejected Supabase Matches',
      type: 'array',
      group: 'review',
      description: 'Fuzzy catalog matches that were inspected and rejected; they must not be merged into this identity.',
      of: [defineArrayMember({
        name: 'rejectedSupabaseMatch',
        title: 'Rejected Supabase Match',
        type: 'object',
        fields: [
          defineField({name: 'recordId', title: 'Supabase Record ID', type: 'string', validation: (Rule) => Rule.required()}),
          defineField({name: 'name', title: 'Supabase Place Name', type: 'string', validation: (Rule) => Rule.required()}),
          defineField({name: 'reason', title: 'Rejection Reason', type: 'text', rows: 2, validation: (Rule) => Rule.required().max(500)}),
        ],
        preview: {select: {title: 'name', subtitle: 'reason'}},
      })],
    }),
    defineField({
      name: 'canonicalCreationStatus',
      title: 'Canonical Creation Status',
      type: 'string',
      group: 'review',
      options: {list: [
        {title: 'Researching', value: 'researching'},
        {title: 'Editorial review', value: 'editorial_review'},
        {title: 'Approved for a separate Supabase change', value: 'approved_for_supabase'},
        {title: 'Rejected', value: 'rejected'},
      ]},
      initialValue: 'researching',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'sourceAdjudicationStatus',
      title: 'Source Adjudication Status',
      type: 'string',
      group: 'review',
      options: {list: [
        {title: 'Contextual point preference—conflict open', value: 'contextual_point_preference_conflict_open'},
        {title: 'Historic-complex multi-point conflict open', value: 'historic_complex_conflict_open'},
        {title: 'Component evidence partial', value: 'component_evidence_partial'},
        {title: 'Responsible operator found—point missing', value: 'responsible_operator_no_point'},
        {title: 'Official relative identity—point missing', value: 'relative_identity_no_point'},
      ]},
    }),
    defineField({name: 'sourceAdjudicationNotes', title: 'Source Adjudication Notes', type: 'text', rows: 6, group: 'review', validation: (Rule) => Rule.max(2200)}),
    defineField({name: 'adjudicatedAt', title: 'Source Adjudicated', type: 'date', group: 'review'}),
    defineField({name: 'reviewedAt', title: 'Evidence Reviewed', type: 'date', group: 'review', validation: (Rule) => Rule.required()}),
    defineField({name: 'reviewNotes', title: 'Editorial Review Notes', type: 'text', rows: 6, group: 'review', description: 'Record unresolved identity, access, operation, safety, accessibility, duplication, and canonical-model decisions.', validation: (Rule) => Rule.required().max(2200)}),
  ],
  preview: {
    select: {title: 'title', island: 'islandName', feature: 'featureType', status: 'canonicalCreationStatus', locationStatus: 'locationReview.reconciliationStatus', adjudication: 'sourceAdjudicationStatus'},
    prepare({title, island, feature, status, locationStatus, adjudication}) {
      return {title: title || 'Untitled candidate', subtitle: [island, feature, locationStatus, adjudication, status].filter(Boolean).join(' · ')}
    },
  },
  orderings: [
    {title: 'Island and name', name: 'islandName', by: [{field: 'islandName', direction: 'asc'}, {field: 'title', direction: 'asc'}]},
    {title: 'Recently changed', name: 'updated', by: [{field: '_updatedAt', direction: 'desc'}]},
  ],
})
