import {defineArrayMember, defineField, defineType} from 'sanity'

export default defineType({
  name: 'deal',
  title: 'Editorial Deal',
  type: 'document',
  description: 'Campaign copy and placement metadata. Provider inventory is authoritative for live price, availability, and checkout.',
  groups: [
    {name: 'content', title: 'Content', default: true},
    {name: 'offer', title: 'Offer'},
    {name: 'delivery', title: 'Delivery'},
  ],
  fields: [
    defineField({name: 'title', title: 'Title', type: 'string', group: 'content', validation: (Rule) => Rule.required().max(120)}),
    defineField({name: 'slug', title: 'Slug', type: 'slug', group: 'delivery', options: {source: 'title', maxLength: 96}, validation: (Rule) => Rule.required()}),
    defineField({name: 'heroImage', title: 'Hero Image', type: 'contentImage', group: 'content'}),
    defineField({
      name: 'category',
      title: 'Category',
      type: 'string',
      group: 'offer',
      options: {list: [
        {title: 'Hotel', value: 'hotel'},
        {title: 'Resort', value: 'resort'},
        {title: 'Package', value: 'package'},
        {title: 'Activity', value: 'activity'},
        {title: 'Dining', value: 'dining'},
        {title: 'Transport', value: 'transport'},
        {title: 'Destination Campaign', value: 'destination_campaign'},
      ]},
      validation: (Rule) => Rule.required(),
    }),
    defineField({name: 'destination', title: 'Destination', type: 'reference', group: 'offer', to: [{type: 'destination'}]}),
    defineField({name: 'partnerName', title: 'Partner or Provider', type: 'string', group: 'offer', validation: (Rule) => Rule.max(120)}),
    defineField({name: 'description', title: 'Description', type: 'text', rows: 4, group: 'content', validation: (Rule) => Rule.required().max(600)}),
    defineField({name: 'discountPercent', title: 'Discount %', type: 'number', group: 'offer', validation: (Rule) => Rule.min(0).max(100)}),
    defineField({name: 'originalPrice', title: 'Original Display Price (USD)', type: 'number', group: 'offer', validation: (Rule) => Rule.min(0)}),
    defineField({name: 'dealPrice', title: 'Deal Display Price (USD)', type: 'number', group: 'offer', validation: (Rule) => Rule.min(0)}),
    defineField({name: 'priceNote', title: 'Price Note', type: 'string', group: 'offer', description: 'Example: From, per night, per person, or taxes excluded.', validation: (Rule) => Rule.max(100)}),
    defineField({name: 'termsSummary', title: 'Terms Summary', type: 'text', rows: 4, group: 'offer', validation: (Rule) => Rule.max(1200)}),
    defineField({name: 'ctaLabel', title: 'CTA Button Label', type: 'string', group: 'offer', initialValue: 'View Deal', validation: (Rule) => Rule.required().max(40)}),
    defineField({name: 'ctaUrl', title: 'CTA URL', type: 'url', group: 'offer', validation: (Rule) => Rule.uri({scheme: ['https']})}),
    defineField({name: 'providerRecordId', title: 'Provider or Supabase Record ID', type: 'string', group: 'offer'}),
    defineField({name: 'validFrom', title: 'Valid From', type: 'datetime', group: 'offer'}),
    defineField({name: 'validUntil', title: 'Valid Until', type: 'datetime', group: 'offer'}),
    defineField({name: 'sponsored', title: 'Sponsored Placement', type: 'boolean', group: 'delivery', initialValue: false}),
    defineField({name: 'sponsorshipLabel', title: 'Disclosure Label', type: 'string', group: 'delivery', hidden: ({parent}) => !parent?.sponsored, initialValue: 'Sponsored', validation: (Rule) => Rule.max(40)}),
    defineField({name: 'active', title: 'Active', type: 'boolean', group: 'delivery', initialValue: true}),
    defineField({name: 'featured', title: 'Featured', type: 'boolean', group: 'delivery', initialValue: false}),
    defineField({name: 'order', title: 'Display Order', type: 'number', group: 'delivery', initialValue: 99}),
    defineField({
      name: 'channels',
      title: 'Delivery Channels',
      type: 'array',
      group: 'delivery',
      of: [defineArrayMember({type: 'string'})],
      options: {list: [{title: 'Web', value: 'web'}, {title: 'Mobile', value: 'mobile'}]},
      initialValue: ['web', 'mobile'],
      validation: (Rule) => Rule.required().min(1),
    }),
    defineField({name: 'reviewedAt', title: 'Last Verified', type: 'date', group: 'delivery'}),
    defineField({name: 'source', title: 'Imported Source', type: 'contentSource', group: 'delivery'}),
  ],
  preview: {select: {title: 'title', media: 'heroImage', category: 'category', partner: 'partnerName', active: 'active'}, prepare({title, media, category, partner, active}) { return {title: title || 'Untitled deal', subtitle: [active === false ? 'Inactive' : 'Active', category, partner].filter(Boolean).join(' · '), media} }},
  orderings: [
    {title: 'Ending soon', name: 'validUntilAsc', by: [{field: 'validUntil', direction: 'asc'}]},
    {title: 'Featured and manual order', name: 'featuredOrder', by: [{field: 'featured', direction: 'desc'}, {field: 'order', direction: 'asc'}]},
  ],
})
