import {defineArrayMember, defineField, defineType} from 'sanity'

export default defineType({
  name: 'destination',
  title: 'Destination',
  type: 'document',
  description: 'Editorial island profile joined to the canonical Supabase islands row through Island ID.',
  groups: [
    {name: 'overview', title: 'Overview', default: true},
    {name: 'planning', title: 'Trip Planning'},
    {name: 'media', title: 'Media'},
    {name: 'delivery', title: 'Delivery'},
  ],
  fields: [
    defineField({name: 'name', title: 'Name', type: 'string', group: 'overview', validation: (Rule) => Rule.required().max(100)}),
    defineField({
      name: 'slug',
      title: 'Public Slug',
      type: 'slug',
      group: 'delivery',
      options: {source: 'name', maxLength: 96},
      description: 'Canonical traveler-facing slug used by destination URLs.',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'islandId',
      title: 'Canonical Island ID',
      description: 'Must exactly match the Supabase islands.slug and the app/web route slug (for example eleuthera-harbour-island).',
      type: 'string',
      group: 'delivery',
      validation: (Rule) => Rule.required().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),
    }),
    defineField({
      name: 'routeAliases',
      title: 'Legacy Slug Aliases',
      type: 'array',
      group: 'delivery',
      description: 'Old or shorthand slugs used only for redirects and lookup compatibility.',
      of: [defineArrayMember({type: 'string', validation: (Rule) => Rule.regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/)})],
      options: {layout: 'tags'},
    }),
    defineField({name: 'tagline', title: 'Tagline', type: 'string', group: 'overview', validation: (Rule) => Rule.required().max(140)}),
    defineField({name: 'overview', title: 'Overview', type: 'richText', group: 'overview', validation: (Rule) => Rule.required().min(1).warning('Add an editorial overview before featuring this destination.')}),
    defineField({name: 'heroImage', title: 'Hero Image', type: 'contentImage', group: 'media'}),
    defineField({
      name: 'highlights',
      title: 'Highlights',
      type: 'array',
      group: 'overview',
      of: [
        defineArrayMember({
          name: 'destinationHighlight',
          title: 'Highlight',
          type: 'object',
          fields: [
            defineField({name: 'label', title: 'Label', type: 'string', validation: (Rule) => Rule.required().max(80)}),
            defineField({name: 'icon', title: 'Icon Name or Emoji', type: 'string', validation: (Rule) => Rule.max(40)}),
            defineField({name: 'description', title: 'Description', type: 'text', rows: 2, validation: (Rule) => Rule.max(240)}),
          ],
          preview: {select: {title: 'label', subtitle: 'description'}},
        }),
      ],
      validation: (Rule) => Rule.max(12),
    }),
    defineField({name: 'bestTimeToVisit', title: 'Best Time to Visit', type: 'string', group: 'planning', validation: (Rule) => Rule.max(180)}),
    defineField({name: 'gettingThere', title: 'Getting There', type: 'text', rows: 5, group: 'planning', validation: (Rule) => Rule.max(1200)}),
    defineField({
      name: 'airports',
      title: 'Airport & Ferry Gateways',
      type: 'array',
      group: 'planning',
      of: [
        defineArrayMember({
          name: 'gateway',
          title: 'Gateway',
          type: 'object',
          fields: [
            defineField({name: 'code', title: 'IATA Code', type: 'string', validation: (Rule) => Rule.uppercase().length(3)}),
            defineField({name: 'name', title: 'Name', type: 'string', validation: (Rule) => Rule.required().max(120)}),
            defineField({name: 'type', title: 'Type', type: 'string', options: {list: [{title: 'Airport', value: 'airport'}, {title: 'Ferry or water taxi', value: 'ferry'}, {title: 'Port', value: 'port'}]}, validation: (Rule) => Rule.required()}),
            defineField({name: 'note', title: 'Traveler Note', type: 'text', rows: 2, validation: (Rule) => Rule.max(300)}),
          ],
          preview: {select: {title: 'name', code: 'code', type: 'type'}, prepare({title, code, type}) { return {title, subtitle: [code, type].filter(Boolean).join(' · ')} }},
        }),
      ],
    }),
    defineField({
      name: 'tripFit',
      title: 'Trip Fit',
      type: 'object',
      group: 'planning',
      fields: [
        defineField({name: 'vibe', title: 'Vibe', type: 'string', validation: (Rule) => Rule.max(80)}),
        defineField({name: 'recommendedStay', title: 'Recommended Stay', type: 'string', description: 'Example: 4–6 days', validation: (Rule) => Rule.max(40)}),
        defineField({name: 'pace', title: 'Pace', type: 'string', validation: (Rule) => Rule.max(60)}),
        defineField({name: 'bestFor', title: 'Best For', type: 'array', of: [defineArrayMember({type: 'string'})], options: {layout: 'tags'}}),
        defineField({name: 'notIdealFor', title: 'Not Ideal For', type: 'text', rows: 2, validation: (Rule) => Rule.max(300)}),
      ],
    }),
    defineField({name: 'practicalNotes', title: 'Practical Notes', type: 'richText', group: 'planning'}),
    defineField({name: 'faqs', title: 'Destination FAQs', type: 'array', group: 'planning', of: [defineArrayMember({type: 'faqItem'})], validation: (Rule) => Rule.max(12)}),
    defineField({name: 'gallery', title: 'Gallery', type: 'array', group: 'media', of: [defineArrayMember({type: 'contentImage'})], validation: (Rule) => Rule.max(20)}),
    defineField({name: 'featured', title: 'Featured', type: 'boolean', group: 'delivery', initialValue: false}),
    defineField({name: 'order', title: 'Sort Order', type: 'number', group: 'delivery', initialValue: 99}),
    defineField({
      name: 'evidenceSources',
      title: 'Editorial Evidence Sources',
      type: 'array',
      group: 'delivery',
      description: 'Reviewed repository sources supporting this profile. Operational details still require a fresh responsible-source check.',
      of: [defineArrayMember({type: 'reference', to: [{type: 'researchSource'}]})],
    }),
    defineField({
      name: 'editorialReviewStatus',
      title: 'Editorial Evidence Status',
      type: 'string',
      group: 'delivery',
      options: {list: [
        {title: 'Legacy — not evidence reviewed', value: 'legacy_unreviewed'},
        {title: 'Researching', value: 'researching'},
        {title: 'Ready for editorial review', value: 'ready_for_review'},
        {title: 'Blocked', value: 'blocked'},
        {title: 'Approved', value: 'approved'},
      ]},
    }),
    defineField({
      name: 'editorialReviewNotes',
      title: 'Editorial Evidence Notes',
      type: 'text',
      rows: 5,
      group: 'delivery',
      validation: (Rule) => Rule.max(1800),
    }),
    defineField({
      name: 'channels',
      title: 'Delivery Channels',
      type: 'array',
      group: 'delivery',
      of: [defineArrayMember({type: 'string'})],
      options: {list: [{title: 'Web', value: 'web'}, {title: 'Mobile', value: 'mobile'}, {title: 'Buddy planning context', value: 'buddy'}]},
      initialValue: ['web', 'mobile', 'buddy'],
      validation: (Rule) => Rule.required().min(1),
    }),
    defineField({name: 'reviewedAt', title: 'Last Reviewed', type: 'date', group: 'delivery'}),
    defineField({name: 'source', title: 'Imported Source', type: 'contentSource', group: 'delivery'}),
    defineField({name: 'seo', title: 'Search & Sharing', type: 'seo', group: 'delivery'}),
  ],
  preview: {
    select: {title: 'name', media: 'heroImage', islandId: 'islandId', featured: 'featured'},
    prepare({title, media, islandId, featured}) {
      return {title: title || 'Untitled destination', subtitle: `${islandId ?? 'Island ID missing'}${featured ? ' · Featured' : ''}`, media}
    },
  },
  orderings: [{title: 'Manual order', name: 'manualOrder', by: [{field: 'order', direction: 'asc'}, {field: 'name', direction: 'asc'}]}],
})
