import {defineArrayMember, defineField, defineType} from 'sanity'

export default defineType({
  name: 'experience',
  title: 'Editorial Experience',
  type: 'document',
  description: 'An editorially curated thing to do. Canonical place inventory, ratings, live prices, and availability remain in Supabase/provider systems.',
  groups: [
    {name: 'content', title: 'Content', default: true},
    {name: 'planning', title: 'Planning'},
    {name: 'delivery', title: 'Delivery'},
  ],
  fields: [
    defineField({name: 'title', title: 'Title', type: 'string', group: 'content', validation: (Rule) => Rule.required().max(120)}),
    defineField({name: 'slug', title: 'Slug', type: 'slug', group: 'delivery', options: {source: 'title', maxLength: 96}, validation: (Rule) => Rule.required()}),
    defineField({name: 'heroImage', title: 'Hero Image', type: 'contentImage', group: 'content'}),
    defineField({
      name: 'category',
      title: 'Category',
      type: 'string',
      group: 'planning',
      options: {list: [
        {title: 'Water Sports', value: 'water_sports'},
        {title: 'Snorkeling & Diving', value: 'snorkeling_diving'},
        {title: 'Boating & Sailing', value: 'boating_sailing'},
        {title: 'Fishing', value: 'fishing'},
        {title: 'Nature & Wildlife', value: 'nature_wildlife'},
        {title: 'Culture & Heritage', value: 'cultural'},
        {title: 'Food & Culinary', value: 'food_culinary'},
        {title: 'Nightlife', value: 'nightlife'},
        {title: 'Family', value: 'family'},
        {title: 'Wellness & Spa', value: 'wellness_spa'},
        {title: 'Shopping & Markets', value: 'shopping_markets'},
      ]},
      validation: (Rule) => Rule.required(),
    }),
    defineField({name: 'destination', title: 'Destination', type: 'reference', group: 'planning', to: [{type: 'destination'}], validation: (Rule) => Rule.required()}),
    defineField({name: 'shortDescription', title: 'Short Description', type: 'text', rows: 3, group: 'content', validation: (Rule) => Rule.required().max(240)}),
    defineField({name: 'description', title: 'Description', type: 'richText', group: 'content', validation: (Rule) => Rule.required().min(1).warning('Add the full editorial description before featuring this experience.')}),
    defineField({
      name: 'priceRange',
      title: 'Planning Price Range',
      type: 'string',
      group: 'planning',
      description: 'General planning guidance only; live prices must come from provider inventory.',
      options: {list: [
        {title: 'Free', value: 'free'},
        {title: '$ (Under $50)', value: '$'},
        {title: '$$ ($50–$150)', value: '$$'},
        {title: '$$$ ($150+)', value: '$$$'},
      ]},
    }),
    defineField({name: 'durationHours', title: 'Typical Duration (hours)', type: 'number', group: 'planning', validation: (Rule) => Rule.min(0.25).max(72)}),
    defineField({name: 'bestFor', title: 'Best For', type: 'array', group: 'planning', of: [defineArrayMember({type: 'string'})], options: {layout: 'tags'}}),
    defineField({name: 'bookingUrl', title: 'Editorial Booking URL', type: 'url', group: 'planning', description: 'Optional external attribution link. In-product booking should use canonical provider records.', validation: (Rule) => Rule.uri({scheme: ['https']})}),
    defineField({name: 'supabaseRecordId', title: 'Supabase Place or Activity ID', type: 'string', group: 'planning'}),
    defineField({name: 'tips', title: 'Traveler Tips', type: 'array', group: 'planning', of: [defineArrayMember({type: 'string'})], validation: (Rule) => Rule.max(12)}),
    defineField({name: 'safetyNote', title: 'Safety or Suitability Note', type: 'text', rows: 3, group: 'planning', validation: (Rule) => Rule.max(500)}),
    defineField({name: 'featured', title: 'Featured', type: 'boolean', group: 'delivery', initialValue: false}),
    defineField({name: 'order', title: 'Display Order', type: 'number', group: 'delivery', initialValue: 99}),
    defineField({name: 'active', title: 'Active', type: 'boolean', group: 'delivery', initialValue: true}),
    defineField({
      name: 'channels',
      title: 'Delivery Channels',
      type: 'array',
      group: 'delivery',
      of: [defineArrayMember({type: 'string'})],
      options: {list: [{title: 'Web', value: 'web'}, {title: 'Mobile', value: 'mobile'}, {title: 'Buddy planning context', value: 'buddy'}]},
      initialValue: ['web', 'mobile'],
      validation: (Rule) => Rule.required().min(1),
    }),
    defineField({name: 'tags', title: 'Tags', type: 'array', group: 'planning', of: [defineArrayMember({type: 'string'})], options: {layout: 'tags'}}),
    defineField({name: 'publishedAt', title: 'Published At', type: 'datetime', group: 'delivery', initialValue: () => new Date().toISOString()}),
    defineField({name: 'reviewedAt', title: 'Last Reviewed', type: 'date', group: 'delivery'}),
    defineField({name: 'source', title: 'Imported Source', type: 'contentSource', group: 'delivery'}),
    defineField({name: 'seo', title: 'Search & Sharing', type: 'seo', group: 'delivery'}),
  ],
  preview: {select: {title: 'title', media: 'heroImage', category: 'category', destination: 'destination.name'}, prepare({title, media, category, destination}) { return {title: title || 'Untitled experience', subtitle: [category, destination].filter(Boolean).join(' · '), media} }},
  orderings: [{title: 'Featured and manual order', name: 'featuredOrder', by: [{field: 'featured', direction: 'desc'}, {field: 'order', direction: 'asc'}]}],
})
