import {defineArrayMember, defineField, defineType} from 'sanity'

/**
 * Review-only image record. It keeps identity, rights, credit, and alt-text
 * evidence together before an image is copied into traveler-facing content.
 */
export default defineType({
  name: 'imageCandidate',
  title: 'Image Candidate',
  type: 'document',
  description: 'A research-only image candidate. A source-page display is not a reuse license, and this document never delivers an image to web, mobile, or Buddy.',
  groups: [
    {name: 'identity', title: 'Subject & Identity', default: true},
    {name: 'asset', title: 'Image & Intended Use'},
    {name: 'rights', title: 'Rights & Credit'},
    {name: 'review', title: 'Review Gate'},
  ],
  fields: [
    defineField({name: 'title', title: 'Candidate Title', type: 'string', group: 'identity', validation: (Rule) => Rule.required().max(180)}),
    defineField({name: 'destination', title: 'Destination', type: 'reference', group: 'identity', to: [{type: 'destination'}], description: 'Assign only when the exact destination shown is confirmed. Regional or unidentified candidates may remain unassigned during research.'}),
    defineField({
      name: 'relatedPlaces',
      title: 'Related Place Reviews',
      type: 'array',
      group: 'identity',
      description: 'Optional review-only links. These references do not approve a place, point, route, or publication.',
      of: [defineArrayMember({type: 'reference', to: [{type: 'placeEditorial'}, {type: 'canonicalPlaceCandidate'}]})],
    }),
    defineField({name: 'subjectLabel', title: 'Exact Subject Label', type: 'string', group: 'identity', validation: (Rule) => Rule.required().max(180)}),
    defineField({
      name: 'subjectType',
      title: 'Subject Type',
      type: 'string',
      group: 'identity',
      options: {list: [
        {title: 'Destination geography', value: 'destination_geography'},
        {title: 'Community or settlement', value: 'community'},
        {title: 'Place or attraction', value: 'place'},
        {title: 'Accommodation or operator', value: 'operator_property'},
        {title: 'Culture or heritage', value: 'culture_heritage'},
        {title: 'Activity', value: 'activity'},
        {title: 'Map or diagram', value: 'map_diagram'},
        {title: 'Unknown or mixed', value: 'unknown_mixed'},
      ]},
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'identityStatus',
      title: 'Subject Identity Status',
      type: 'string',
      group: 'identity',
      options: {list: [
        {title: 'Confirmed by responsible-source metadata', value: 'responsible_source_confirmed'},
        {title: 'Confirmed by creator/file metadata', value: 'creator_metadata_confirmed'},
        {title: 'Source-page label only', value: 'source_page_label_only'},
        {title: 'Visual review—provisional', value: 'visual_review_provisional'},
        {title: 'Unverified', value: 'unverified'},
        {title: 'Rejected or unavailable', value: 'rejected'},
      ]},
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'identityEvidence',
      title: 'Identity Evidence',
      type: 'array',
      group: 'identity',
      of: [defineArrayMember({type: 'reference', to: [{type: 'researchSource'}]})],
      validation: (Rule) => Rule.required().min(1),
    }),
    defineField({name: 'identityNotes', title: 'Identity Boundary', type: 'text', rows: 5, group: 'identity', validation: (Rule) => Rule.required().max(1600)}),

    defineField({
      name: 'reviewImage',
      title: 'Managed Review Image or External Candidate',
      type: 'contentImage',
      group: 'asset',
      description: 'Use a managed Sanity asset only when reuse terms are documented. Otherwise retain the exact external URL without copying the file.',
      validation: (Rule) => Rule.required().custom((value) => value?.asset?._ref || value?.externalUrl ? true : 'Add either a managed asset or an exact external candidate URL.'),
    }),
    defineField({name: 'sourceAssetId', title: 'Source Asset ID', type: 'string', group: 'asset', description: 'For example a NASA photo number, controlled-library ID, or Commons filename.', validation: (Rule) => Rule.max(180)}),
    defineField({name: 'sourceAssetUrl', title: 'Original Asset URL', type: 'url', group: 'asset', validation: (Rule) => Rule.required().uri({scheme: ['https']})}),
    defineField({name: 'sourcePageUrl', title: 'Source Record or Display Page', type: 'url', group: 'asset', validation: (Rule) => Rule.required().uri({scheme: ['https']})}),
    defineField({
      name: 'intendedUses',
      title: 'Candidate Uses',
      type: 'array',
      group: 'asset',
      of: [defineArrayMember({type: 'string'})],
      options: {layout: 'tags', list: [
        {title: 'Destination hero', value: 'destination_hero'},
        {title: 'Destination gallery', value: 'destination_gallery'},
        {title: 'Place hero', value: 'place_hero'},
        {title: 'Place gallery', value: 'place_gallery'},
        {title: 'Map or geographic context', value: 'map_context'},
        {title: 'Editorial article', value: 'editorial_article'},
        {title: 'Social or sharing', value: 'social_sharing'},
      ]},
      validation: (Rule) => Rule.required().min(1),
    }),
    defineField({name: 'captureDate', title: 'Capture or Creation Date', type: 'date', group: 'asset'}),
    defineField({name: 'width', title: 'Pixel Width', type: 'number', group: 'asset', validation: (Rule) => Rule.integer().positive()}),
    defineField({name: 'height', title: 'Pixel Height', type: 'number', group: 'asset', validation: (Rule) => Rule.integer().positive()}),
    defineField({name: 'checksumSha256', title: 'SHA-256 of Reviewed File', type: 'string', group: 'asset', validation: (Rule) => Rule.regex(/^[a-f0-9]{64}$/).warning('Use a lowercase 64-character SHA-256 when a file was reviewed or uploaded.')}),

    defineField({name: 'creator', title: 'Creator or Photographer', type: 'string', group: 'rights', validation: (Rule) => Rule.max(180)}),
    defineField({name: 'rightsHolder', title: 'Rights Holder or Source Agency', type: 'string', group: 'rights', validation: (Rule) => Rule.required().max(180)}),
    defineField({
      name: 'rightsStatus',
      title: 'Reuse Status',
      type: 'string',
      group: 'rights',
      options: {list: [
        {title: 'Source display only—not cleared', value: 'source_display_only_not_cleared'},
        {title: 'Controlled library—asset license required', value: 'controlled_library_asset_license_required'},
        {title: 'Permission required', value: 'permission_required'},
        {title: 'Documented open license', value: 'documented_open_license'},
        {title: 'Public domain or government reuse terms', value: 'public_domain_or_government_reuse_terms'},
        {title: 'Direct permission recorded', value: 'direct_permission_recorded'},
        {title: 'Rejected or unavailable', value: 'rejected'},
      ]},
      validation: (Rule) => Rule.required(),
    }),
    defineField({name: 'licenseName', title: 'License or Reuse Terms', type: 'string', group: 'rights', validation: (Rule) => Rule.max(240)}),
    defineField({name: 'licenseUrl', title: 'License or Terms URL', type: 'url', group: 'rights', validation: (Rule) => Rule.uri({scheme: ['https']})}),
    defineField({name: 'requiredCredit', title: 'Required Credit', type: 'text', rows: 3, group: 'rights', validation: (Rule) => Rule.max(600)}),
    defineField({name: 'usageRestrictions', title: 'Usage Restrictions', type: 'text', rows: 5, group: 'rights', validation: (Rule) => Rule.required().max(1600)}),
    defineField({
      name: 'rightsEvidence',
      title: 'Rights Evidence',
      type: 'array',
      group: 'rights',
      of: [defineArrayMember({type: 'reference', to: [{type: 'researchSource'}]})],
      validation: (Rule) => Rule.required().min(1),
    }),

    defineField({name: 'currentConditionBoundary', title: 'Freshness & Current-condition Boundary', type: 'text', rows: 4, group: 'review', validation: (Rule) => Rule.required().max(1200)}),
    defineField({name: 'altTextDraft', title: 'Factual Alt-text Draft', type: 'string', group: 'review', description: 'Draft only after the exact asset has been selected and visually checked.', validation: (Rule) => Rule.max(180)}),
    defineField({
      name: 'altTextStatus',
      title: 'Alt-text Status',
      type: 'string',
      group: 'review',
      options: {list: [
        {title: 'No exact image selected', value: 'no_exact_image'},
        {title: 'Draft—not reviewed', value: 'draft_unreviewed'},
        {title: 'Reviewed', value: 'reviewed'},
        {title: 'Not applicable', value: 'not_applicable'},
      ]},
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'reviewStatus',
      title: 'Workflow Status',
      type: 'string',
      group: 'review',
      options: {list: [
        {title: 'Researching', value: 'researching'},
        {title: 'Rights review', value: 'rights_review'},
        {title: 'Ready for editorial review', value: 'ready_for_editorial_review'},
        {title: 'Approved', value: 'approved'},
        {title: 'Rejected', value: 'rejected'},
      ]},
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'approvalStatus',
      title: 'Content Approval Status',
      type: 'string',
      group: 'review',
      description: 'Candidates are not connected to delivery until an approved asset is explicitly promoted into traveler-facing content.',
      options: {list: [
        {title: 'Research only', value: 'research_only'},
        {title: 'Approved for separate content change', value: 'approved_for_content'},
        {title: 'Rejected', value: 'rejected'},
      ]},
      initialValue: 'research_only',
      validation: (Rule) => Rule.required(),
    }),
    defineField({name: 'checkedAt', title: 'Checked At', type: 'date', group: 'review', validation: (Rule) => Rule.required()}),
    defineField({name: 'nextReviewAt', title: 'Review Again By', type: 'date', group: 'review', validation: (Rule) => Rule.required()}),
    defineField({name: 'reviewNotes', title: 'Review Notes & Next Action', type: 'text', rows: 7, group: 'review', validation: (Rule) => Rule.required().max(2400)}),
  ],
  preview: {
    select: {title: 'title', destination: 'destination.name', media: 'reviewImage', rights: 'rightsStatus', status: 'reviewStatus'},
    prepare({title, destination, media, rights, status}) {
      return {title: title || 'Untitled image candidate', subtitle: [destination, rights, status].filter(Boolean).join(' · '), media}
    },
  },
  orderings: [
    {title: 'Rights status', name: 'rights', by: [{field: 'rightsStatus', direction: 'asc'}, {field: 'title', direction: 'asc'}]},
    {title: 'Next review', name: 'nextReview', by: [{field: 'nextReviewAt', direction: 'asc'}, {field: 'title', direction: 'asc'}]},
  ],
})
