import {defineArrayMember, defineField, defineType} from 'sanity'

export default defineType({
  name: 'itinerary',
  title: 'Editorial Itinerary',
  type: 'document',
  description: 'Curated itinerary narrative. Live purchasable cruise-day plans, prices, and bookings remain in Supabase.',
  groups: [
    {name: 'overview', title: 'Overview', default: true},
    {name: 'plan', title: 'Plan'},
    {name: 'delivery', title: 'Delivery'},
  ],
  fields: [
    defineField({name: 'title', title: 'Title', type: 'string', group: 'overview', validation: (Rule) => Rule.required().max(120)}),
    defineField({name: 'slug', title: 'Slug', type: 'slug', group: 'delivery', options: {source: 'title', maxLength: 96}, validation: (Rule) => Rule.required()}),
    defineField({name: 'summary', title: 'Summary', type: 'text', rows: 3, group: 'overview', validation: (Rule) => Rule.required().max(300)}),
    defineField({name: 'heroImage', title: 'Hero Image', type: 'contentImage', group: 'overview'}),
    defineField({name: 'destination', title: 'Primary Destination', type: 'reference', group: 'overview', to: [{type: 'destination'}], validation: (Rule) => Rule.required()}),
    defineField({
      name: 'itineraryType',
      title: 'Itinerary Type',
      type: 'string',
      group: 'overview',
      options: {
        list: [
          {title: 'Cruise day', value: 'cruise_day'},
          {title: 'One-day island plan', value: 'day_trip'},
          {title: 'Multi-day island stay', value: 'multi_day'},
          {title: 'Island hopping', value: 'island_hopping'},
          {title: 'Theme itinerary', value: 'theme'},
        ],
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({name: 'durationDays', title: 'Duration (days)', type: 'number', group: 'overview', validation: (Rule) => Rule.min(1).max(30)}),
    defineField({name: 'durationHours', title: 'Duration (hours)', type: 'number', group: 'overview', validation: (Rule) => Rule.min(1).max(24)}),
    defineField({
      name: 'bestFor',
      title: 'Best For',
      type: 'array',
      group: 'overview',
      of: [defineArrayMember({type: 'string'})],
      options: {layout: 'tags'},
    }),
    defineField({name: 'introduction', title: 'Introduction', type: 'richText', group: 'plan'}),
    defineField({
      name: 'stops',
      title: 'Stops',
      type: 'array',
      group: 'plan',
      of: [
        defineArrayMember({
          name: 'itineraryStop',
          title: 'Stop',
          type: 'object',
          fields: [
            defineField({name: 'day', title: 'Day', type: 'number', validation: (Rule) => Rule.min(1).max(30)}),
            defineField({name: 'time', title: 'Time or Window', type: 'string', validation: (Rule) => Rule.max(40)}),
            defineField({name: 'title', title: 'Stop Title', type: 'string', validation: (Rule) => Rule.required().max(120)}),
            defineField({name: 'description', title: 'Description', type: 'text', rows: 4, validation: (Rule) => Rule.required().max(800)}),
            defineField({name: 'durationMinutes', title: 'Duration (minutes)', type: 'number', validation: (Rule) => Rule.min(5).max(1440)}),
            defineField({name: 'supabasePlaceId', title: 'Supabase Place ID', type: 'string', description: 'Optional link to canonical place inventory.'}),
            defineField({name: 'mapLabel', title: 'Map or Address Label', type: 'string', validation: (Rule) => Rule.max(180)}),
            defineField({name: 'travelerNote', title: 'Traveler Note', type: 'text', rows: 2, validation: (Rule) => Rule.max(300)}),
          ],
          preview: {select: {title: 'title', time: 'time', day: 'day'}, prepare({title, time, day}) { return {title, subtitle: [day ? `Day ${day}` : null, time].filter(Boolean).join(' · ')} }},
        }),
      ],
      validation: (Rule) => Rule.required().min(1).warning('Add at least one stop before this itinerary is delivered.'),
    }),
    defineField({name: 'logistics', title: 'Logistics & Timing', type: 'richText', group: 'plan'}),
    defineField({name: 'safetyNote', title: 'Safety or Return Buffer Note', type: 'text', rows: 3, group: 'plan', validation: (Rule) => Rule.max(600)}),
    defineField({name: 'sourceRecordId', title: 'Supabase Itinerary ID', type: 'string', group: 'delivery', description: 'Optional bridge to a live priced/operational itinerary record.'}),
    defineField({
      name: 'channels',
      title: 'Delivery Channels',
      type: 'array',
      group: 'delivery',
      of: [defineArrayMember({type: 'string'})],
      options: {list: [{title: 'Web', value: 'web'}, {title: 'Mobile', value: 'mobile'}, {title: 'Buddy planning context', value: 'buddy'}]},
      initialValue: ['web', 'mobile'],
      validation: (Rule) => Rule.required().min(1),
    }),
    defineField({name: 'featured', title: 'Featured', type: 'boolean', group: 'delivery', initialValue: false}),
    defineField({name: 'order', title: 'Display Order', type: 'number', group: 'delivery', initialValue: 99}),
    defineField({name: 'publishedAt', title: 'Published At', type: 'datetime', group: 'delivery', initialValue: () => new Date().toISOString()}),
    defineField({name: 'source', title: 'Imported Source', type: 'contentSource', group: 'delivery'}),
    defineField({name: 'seo', title: 'Search & Sharing', type: 'seo', group: 'delivery'}),
  ],
  preview: {select: {title: 'title', subtitle: 'itineraryType', media: 'heroImage'}},
  orderings: [{title: 'Manual order', name: 'manualOrder', by: [{field: 'featured', direction: 'desc'}, {field: 'order', direction: 'asc'}]}],
})
