import {defineArrayMember, defineField, defineType} from 'sanity'

/** Editor-managed copy and presentation layered over canonical Supabase places. */
export default defineType({
  name: 'placeEditorial',
  title: 'Place Editorial Overlay',
  type: 'document',
  description: 'Manage traveler-facing place copy and media while Supabase remains authoritative for live inventory.',
  groups: [
    {name: 'content', title: 'Editorial Content', default: true},
    {name: 'planning', title: 'Planning Context'},
    {name: 'readiness', title: 'Traveler Readiness'},
    {name: 'source', title: 'Source & Delivery'},
  ],
  fields: [
    defineField({name: 'title', title: 'Place Name', type: 'string', group: 'content', validation: (Rule) => Rule.required().max(140)}),
    defineField({name: 'slug', title: 'Editorial Slug', type: 'slug', group: 'source', options: {source: 'title', maxLength: 96}, validation: (Rule) => Rule.required()}),
    defineField({name: 'destination', title: 'Destination', type: 'reference', group: 'planning', to: [{type: 'destination'}]}),
    defineField({name: 'islandName', title: 'Island Name', type: 'string', group: 'planning'}),
    defineField({name: 'category', title: 'Category', type: 'string', group: 'planning', validation: (Rule) => Rule.required()}),
    defineField({name: 'subcategory', title: 'Subcategory', type: 'string', group: 'planning'}),
    defineField({name: 'shortDescription', title: 'Card Description', type: 'text', rows: 3, group: 'content', validation: (Rule) => Rule.max(300)}),
    defineField({name: 'description', title: 'Full Description', type: 'richText', group: 'content'}),
    defineField({name: 'primaryImage', title: 'Primary Image', type: 'contentImage', group: 'content'}),
    defineField({name: 'gallery', title: 'Gallery', type: 'array', group: 'content', of: [defineArrayMember({type: 'contentImage'})], validation: (Rule) => Rule.max(30)}),
    defineField({name: 'address', title: 'Traveler-facing Address', type: 'string', group: 'planning'}),
    defineField({name: 'website', title: 'Website', type: 'url', group: 'planning', validation: (Rule) => Rule.uri({scheme: ['http', 'https']})}),
    defineField({name: 'phone', title: 'Phone', type: 'string', group: 'planning'}),
    defineField({name: 'openingHours', title: 'Opening Hours Note', type: 'text', rows: 3, group: 'planning'}),
    defineField({name: 'tags', title: 'Tags', type: 'array', group: 'planning', of: [defineArrayMember({type: 'string'})], options: {layout: 'tags'}}),
    defineField({name: 'bestFor', title: 'Best For', type: 'array', group: 'planning', of: [defineArrayMember({type: 'string'})], options: {layout: 'tags'}}),
    defineField({name: 'amenities', title: 'Amenities', type: 'array', group: 'planning', of: [defineArrayMember({type: 'string'})], options: {layout: 'tags'}}),
    defineField({name: 'buddyTips', title: 'Buddy Tips', type: 'array', group: 'planning', of: [defineArrayMember({type: 'string'})]}),
    defineField({name: 'visitorTips', title: 'Visitor Tips', type: 'richText', group: 'planning'}),
    defineField({name: 'accessibilityNotes', title: 'Accessibility Notes', type: 'text', rows: 3, group: 'planning'}),
    defineField({name: 'active', title: 'Editorially Active', type: 'boolean', group: 'source', initialValue: true}),
    defineField({name: 'featured', title: 'Featured', type: 'boolean', group: 'source', initialValue: false}),
    defineField({name: 'channels', title: 'Delivery Channels', type: 'array', group: 'source', of: [defineArrayMember({type: 'string'})], options: {list: [{title: 'Web', value: 'web'}, {title: 'Mobile', value: 'mobile'}, {title: 'Buddy planning context', value: 'buddy'}]}, initialValue: ['web', 'mobile', 'buddy']}),
    defineField({name: 'source', title: 'Imported Source', type: 'contentSource', group: 'source', validation: (Rule) => Rule.required()}),
    defineField({name: 'officialSourceName', title: 'Official Source Name', type: 'string', group: 'source', description: 'The identity as written by the reviewed official source. It may differ from the Supabase catalog name.', validation: (Rule) => Rule.max(180)}),
    defineField({
      name: 'catalogReviewStatus',
      title: 'Catalog Review Status',
      type: 'string',
      group: 'source',
      options: {list: [
        {title: 'Exact candidate — gates incomplete', value: 'exact_candidate'},
        {title: 'Source-backed name variant', value: 'name_variant'},
        {title: 'Location missing or invalid', value: 'location_blocked'},
        {title: 'Island assignment conflict', value: 'island_assignment_conflict'},
        {title: 'Editorial review', value: 'editorial_review'},
        {title: 'Approved', value: 'approved'},
        {title: 'Rejected', value: 'rejected'},
      ]},
    }),
    defineField({
      name: 'evidenceSources',
      title: 'Identity Evidence',
      type: 'array',
      group: 'source',
      of: [defineArrayMember({type: 'reference', to: [{type: 'researchSource'}]})],
    }),
    defineField({name: 'catalogReviewNotes', title: 'Catalog Review Notes', type: 'text', rows: 5, group: 'source', validation: (Rule) => Rule.max(1600)}),
    defineField({name: 'catalogLocationReview', title: 'Official Location Evidence', type: 'placeLocationReview', group: 'source'}),
    defineField({name: 'catalogTravelerReadinessReview', title: 'Traveler Readiness Evidence', type: 'placeTravelerReadinessReview', group: 'readiness'}),
    defineField({name: 'catalogContentReadinessReview', title: 'Accessibility, Copy & Media Evidence', type: 'placeContentReadinessReview', group: 'readiness'}),
    defineField({name: 'reviewedAt', title: 'Last Editorial Review', type: 'date', group: 'source'}),
    defineField({name: 'seo', title: 'Search & Sharing', type: 'seo', group: 'source'}),
  ],
  preview: {
    select: {title: 'title', category: 'category', island: 'islandName', media: 'primaryImage', active: 'active', reviewStatus: 'catalogReviewStatus'},
    prepare({title, category, island, media, active, reviewStatus}) {
      return {title: title || 'Untitled place', subtitle: [active === false ? 'Inactive' : null, reviewStatus, category, island].filter(Boolean).join(' · '), media}
    },
  },
  orderings: [
    {title: 'Island and name', name: 'islandName', by: [{field: 'islandName', direction: 'asc'}, {field: 'title', direction: 'asc'}]},
    {title: 'Recently imported or changed', name: 'updated', by: [{field: '_updatedAt', direction: 'desc'}]},
  ],
})
