import {defineArrayMember, defineField, defineType} from 'sanity'

/** A durable citation record used by island facts and coverage audits. */
export default defineType({
  name: 'researchSource',
  title: 'Research Source',
  type: 'document',
  description: 'A reviewed source with enough provenance to support traveler-facing facts.',
  groups: [
    {name: 'identity', title: 'Source', default: true},
    {name: 'scope', title: 'Coverage'},
    {name: 'review', title: 'Review'},
  ],
  fields: [
    defineField({name: 'title', title: 'Source Title', type: 'string', group: 'identity', validation: (Rule) => Rule.required().max(180)}),
    defineField({name: 'url', title: 'Canonical URL', type: 'url', group: 'identity', validation: (Rule) => Rule.required().uri({scheme: ['https']})}),
    defineField({name: 'publisher', title: 'Publisher', type: 'string', group: 'identity', validation: (Rule) => Rule.required().max(140)}),
    defineField({
      name: 'checksumSha256',
      title: 'Source SHA-256',
      type: 'string',
      group: 'identity',
      description: 'Hash of the captured source or normalized source segment. Used with canonical URL to prevent duplicate intake.',
      validation: (Rule) => Rule.regex(/^[a-f0-9]{64}$/).warning('Use a lowercase 64-character SHA-256 digest.'),
    }),
    defineField({
      name: 'sourcePackage',
      title: 'Source Package',
      type: 'string',
      group: 'identity',
      description: 'Stable identifier for the controlled research intake that produced this source.',
      validation: (Rule) => Rule.max(140),
    }),
    defineField({
      name: 'sourceClass',
      title: 'Source Class',
      type: 'string',
      group: 'identity',
      options: {list: [
        {title: 'National tourism authority', value: 'national_tourism'},
        {title: 'Government or regulator', value: 'government'},
        {title: 'Conservation authority', value: 'conservation'},
        {title: 'Transport operator', value: 'transport_operator'},
        {title: 'Venue or activity operator', value: 'operator'},
        {title: 'Industry body', value: 'industry_body'},
        {title: 'Independent editorial source', value: 'independent_editorial'},
        {title: 'Internal product or repository evidence', value: 'internal_product'},
      ]},
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'authorityLevel',
      title: 'Authority Level',
      type: 'string',
      group: 'identity',
      options: {list: [
        {title: 'Primary / official', value: 'primary'},
        {title: 'Authoritative corroboration', value: 'corroborating'},
        {title: 'Discovery lead only', value: 'discovery_only'},
      ]},
      validation: (Rule) => Rule.required(),
    }),
    defineField({name: 'destinations', title: 'Related Destinations', type: 'array', group: 'scope', of: [defineArrayMember({type: 'reference', to: [{type: 'destination'}]})]}),
    defineField({
      name: 'topics',
      title: 'Topics Covered',
      type: 'array',
      group: 'scope',
      of: [defineArrayMember({type: 'string'})],
      options: {layout: 'tags', list: [
        {title: 'Overview & identity', value: 'overview'},
        {title: 'Access & transport', value: 'access'},
        {title: 'Stays', value: 'stays'},
        {title: 'Food & drink', value: 'food'},
        {title: 'Experiences', value: 'experiences'},
        {title: 'Beaches & nature', value: 'nature'},
        {title: 'Culture & history', value: 'culture'},
        {title: 'Seasonality & weather', value: 'seasonality'},
        {title: 'Safety & practical guidance', value: 'safety'},
        {title: 'Accessibility', value: 'accessibility'},
        {title: 'Image identity, rights & credit', value: 'media'},
      ]},
      validation: (Rule) => Rule.required().min(1),
    }),
    defineField({name: 'checkedAt', title: 'Last Checked', type: 'date', group: 'review', validation: (Rule) => Rule.required()}),
    defineField({name: 'nextReviewAt', title: 'Review Again By', type: 'date', group: 'review'}),
    defineField({name: 'reviewPlan', title: 'Ownership & Freshness Plan', type: 'researchSourceReviewPlan', group: 'review'}),
    defineField({
      name: 'replacementSources',
      title: 'Recorded Replacement Sources',
      description: 'Current sources that replace the unavailable record for a bounded claim. This does not revive the old URL or approve claims beyond the replacement sources’ scope.',
      type: 'array',
      group: 'review',
      of: [defineArrayMember({type: 'reference', to: [{type: 'researchSource'}]})],
    }),
    defineField({
      name: 'replacementBoundary',
      title: 'Replacement Boundary',
      description: 'What the replacement set resolves and which operator, access, safety, accessibility, coordinate, or rights claims remain open.',
      type: 'text',
      rows: 4,
      group: 'review',
      validation: (Rule) => Rule.max(1200),
    }),
    defineField({
      name: 'status',
      title: 'Status',
      type: 'string',
      group: 'review',
      options: {list: [
        {title: 'Active', value: 'active'},
        {title: 'Needs recheck', value: 'needs_recheck'},
        {title: 'Unavailable', value: 'unavailable'},
        {title: 'Rejected', value: 'rejected'},
      ]},
      initialValue: 'active',
      validation: (Rule) => Rule.required(),
    }),
    defineField({name: 'notes', title: 'Research Notes', type: 'text', rows: 4, group: 'review', validation: (Rule) => Rule.max(1200)}),
  ],
  preview: {
    select: {title: 'title', publisher: 'publisher', authority: 'authorityLevel', status: 'status'},
    prepare({title, publisher, authority, status}) {
      return {title: title || 'Untitled source', subtitle: [publisher, authority, status].filter(Boolean).join(' · ')}
    },
  },
  orderings: [{title: 'Recently checked', name: 'checked', by: [{field: 'checkedAt', direction: 'desc'}]}],
})
