import {defineArrayMember, defineField, defineType} from 'sanity'

export default defineType({
  name: 'siteSettings',
  title: 'Site & App Settings',
  type: 'document',
  groups: [
    {name: 'brand', title: 'Brand & Homepage', default: true},
    {name: 'merchandising', title: 'Featured Content'},
    {name: 'support', title: 'Support & Social'},
    {name: 'seo', title: 'Search & Sharing'},
  ],
  fields: [
    defineField({name: 'title', title: 'Internal Title', type: 'string', group: 'brand', initialValue: 'Baha Buddy Site & App Settings', readOnly: true}),
    defineField({name: 'heroHeadline', title: 'Homepage Hero Headline', type: 'string', group: 'brand', validation: (Rule) => Rule.max(100)}),
    defineField({name: 'heroSubheadline', title: 'Homepage Hero Subheadline', type: 'text', rows: 3, group: 'brand', validation: (Rule) => Rule.max(240)}),
    defineField({name: 'heroImage', title: 'Homepage Hero Image', type: 'contentImage', group: 'brand'}),
    defineField({
      name: 'heroActions',
      title: 'Homepage Hero Actions',
      type: 'array',
      group: 'brand',
      of: [defineArrayMember({type: 'callToAction'})],
      validation: (Rule) => Rule.max(3),
    }),
    defineField({
      name: 'announcementBar',
      title: 'Announcement Bar',
      type: 'object',
      group: 'brand',
      fields: [
        defineField({name: 'enabled', title: 'Enabled', type: 'boolean', initialValue: false}),
        defineField({name: 'text', title: 'Text', type: 'string', validation: (Rule) => Rule.max(140)}),
        defineField({name: 'url', title: 'External URL', type: 'url', validation: (Rule) => Rule.uri({scheme: ['https']})}),
        defineField({name: 'internalPath', title: 'Internal Path', type: 'string', description: 'Optional Baha Buddy path beginning with /.'}),
        defineField({name: 'startsAt', title: 'Starts At', type: 'datetime'}),
        defineField({name: 'endsAt', title: 'Ends At', type: 'datetime'}),
      ],
    }),
    defineField({name: 'featuredArticle', title: 'Primary Featured Article', type: 'reference', group: 'merchandising', to: [{type: 'article'}]}),
    defineField({name: 'featuredDestinations', title: 'Featured Destinations', type: 'array', group: 'merchandising', of: [defineArrayMember({type: 'reference', to: [{type: 'destination'}]})], validation: (Rule) => Rule.max(8)}),
    defineField({name: 'featuredExperiences', title: 'Featured Experiences', type: 'array', group: 'merchandising', of: [defineArrayMember({type: 'reference', to: [{type: 'experience'}]})], validation: (Rule) => Rule.max(8)}),
    defineField({name: 'featuredCollections', title: 'Featured Collections', type: 'array', group: 'merchandising', of: [defineArrayMember({type: 'reference', to: [{type: 'contentCollection'}]})], validation: (Rule) => Rule.max(8)}),
    defineField({name: 'featuredTours', title: 'Featured Guided Tours', type: 'array', group: 'merchandising', of: [defineArrayMember({type: 'reference', to: [{type: 'guidedTour'}]})], validation: (Rule) => Rule.max(8)}),
    defineField({
      name: 'starterPrompts',
      title: 'Buddy Starter Prompts',
      type: 'array',
      group: 'merchandising',
      description: 'Short, high-value prompts used in home and Explore entry points.',
      of: [
        defineArrayMember({
          name: 'starterPrompt',
          title: 'Starter Prompt',
          type: 'object',
          fields: [
            defineField({name: 'label', title: 'Label', type: 'string', validation: (Rule) => Rule.required().max(50)}),
            defineField({name: 'prompt', title: 'Prompt', type: 'text', rows: 3, validation: (Rule) => Rule.required().max(500)}),
            defineField({name: 'channels', title: 'Channels', type: 'array', of: [defineArrayMember({type: 'string'})], options: {list: [{title: 'Web', value: 'web'}, {title: 'Mobile', value: 'mobile'}]}}),
          ],
          preview: {select: {title: 'label', subtitle: 'prompt'}},
        }),
      ],
      validation: (Rule) => Rule.max(12),
    }),
    defineField({
      name: 'supportContacts',
      title: 'Support Contacts',
      type: 'object',
      group: 'support',
      fields: [
        defineField({name: 'supportEmail', title: 'Support Email', type: 'string', validation: (Rule) => Rule.email()}),
        defineField({name: 'privacyEmail', title: 'Privacy Email', type: 'string', validation: (Rule) => Rule.email()}),
        defineField({name: 'partnerEmail', title: 'Partner Email', type: 'string', validation: (Rule) => Rule.email()}),
        defineField({name: 'pressEmail', title: 'Press Email', type: 'string', validation: (Rule) => Rule.email()}),
      ],
    }),
    defineField({
      name: 'socialLinks',
      title: 'Social Links',
      type: 'object',
      group: 'support',
      fields: [
        defineField({name: 'instagram', title: 'Instagram URL', type: 'url', validation: (Rule) => Rule.uri({scheme: ['https']})}),
        defineField({name: 'facebook', title: 'Facebook URL', type: 'url', validation: (Rule) => Rule.uri({scheme: ['https']})}),
        defineField({name: 'tiktok', title: 'TikTok URL', type: 'url', validation: (Rule) => Rule.uri({scheme: ['https']})}),
        defineField({name: 'twitter', title: 'X / Twitter URL', type: 'url', validation: (Rule) => Rule.uri({scheme: ['https']})}),
        defineField({name: 'youtube', title: 'YouTube URL', type: 'url', validation: (Rule) => Rule.uri({scheme: ['https']})}),
      ],
    }),
    defineField({name: 'appStoreUrl', title: 'App Store URL', type: 'url', group: 'support', validation: (Rule) => Rule.uri({scheme: ['https']})}),
    defineField({name: 'googlePlayUrl', title: 'Google Play URL', type: 'url', group: 'support', validation: (Rule) => Rule.uri({scheme: ['https']})}),
    defineField({name: 'primaryNavigation', title: 'Primary Navigation', type: 'reference', group: 'support', to: [{type: 'navigation'}]}),
    defineField({name: 'footerNavigation', title: 'Footer Navigation', type: 'reference', group: 'support', to: [{type: 'navigation'}]}),
    defineField({name: 'defaultSeo', title: 'Default Search & Sharing', type: 'seo', group: 'seo'}),
    defineField({name: 'lastReviewedAt', title: 'Settings Last Reviewed', type: 'date', group: 'seo'}),
  ],
  preview: {prepare() { return {title: 'Site & App Settings', subtitle: 'Global editorial configuration'} }},
})
