import {defineArrayMember, defineField, defineType} from 'sanity'

export default defineType({
  name: 'tip',
  title: 'Travel Tip',
  type: 'document',
  fields: [
    defineField({name: 'title', title: 'Internal Title', type: 'string', description: 'Used in Studio; the delivered card uses the body.', validation: (Rule) => Rule.required().max(100)}),
    defineField({name: 'body', title: 'Tip', type: 'text', rows: 4, validation: (Rule) => Rule.required().max(500)}),
    defineField({
      name: 'category',
      title: 'Category',
      type: 'string',
      options: {list: [
        {title: 'Local Knowledge', value: 'local_knowledge'},
        {title: 'Safety', value: 'safety'},
        {title: 'Money & Budget', value: 'money_budget'},
        {title: 'Getting Around', value: 'getting_around'},
        {title: 'Food & Drink', value: 'food_drink'},
        {title: 'Culture & Etiquette', value: 'culture_etiquette'},
        {title: 'Weather', value: 'weather'},
        {title: 'Packing', value: 'packing'},
        {title: 'Cruise Day', value: 'cruise_day'},
        {title: 'Family Travel', value: 'family_travel'},
        {title: 'Accessibility', value: 'accessibility'},
      ]},
      validation: (Rule) => Rule.required(),
    }),
    defineField({name: 'destination', title: 'Destination (optional)', type: 'reference', to: [{type: 'destination'}]}),
    defineField({name: 'emoji', title: 'Emoji', type: 'string', description: 'Single emoji displayed with the tip.', validation: (Rule) => Rule.max(4)}),
    defineField({name: 'audiences', title: 'Traveler Audiences', type: 'array', of: [defineArrayMember({type: 'string'})], options: {layout: 'tags'}}),
    defineField({name: 'seasonalNote', title: 'Seasonal Window or Note', type: 'string', validation: (Rule) => Rule.max(120)}),
    defineField({name: 'sourceUrl', title: 'Editorial Source', type: 'url', description: 'Optional authoritative source used to verify the tip.', validation: (Rule) => Rule.uri({scheme: ['https']})}),
    defineField({
      name: 'channels',
      title: 'Delivery Channels',
      type: 'array',
      of: [defineArrayMember({type: 'string'})],
      options: {list: [{title: 'Web', value: 'web'}, {title: 'Mobile', value: 'mobile'}, {title: 'Buddy planning context', value: 'buddy'}]},
      initialValue: ['web', 'mobile'],
      validation: (Rule) => Rule.required().min(1),
    }),
    defineField({name: 'featured', title: 'Featured', type: 'boolean', initialValue: false}),
    defineField({name: 'order', title: 'Display Order', type: 'number', initialValue: 99}),
    defineField({name: 'publishedAt', title: 'Published At', type: 'datetime', initialValue: () => new Date().toISOString()}),
    defineField({name: 'reviewedAt', title: 'Last Reviewed', type: 'date'}),
    defineField({name: 'source', title: 'Imported Source', type: 'contentSource'}),
    defineField({name: 'tags', title: 'Tags', type: 'array', of: [defineArrayMember({type: 'string'})], options: {layout: 'tags'}}),
  ],
  preview: {select: {title: 'title', category: 'category', destination: 'destination.name'}, prepare({title, category, destination}) { return {title: title || 'Untitled tip', subtitle: [category?.replace(/_/g, ' '), destination].filter(Boolean).join(' · ')} }},
  orderings: [
    {title: 'Featured and manual order', name: 'featuredOrder', by: [{field: 'featured', direction: 'desc'}, {field: 'order', direction: 'asc'}]},
    {title: 'Newest first', name: 'publishedDesc', by: [{field: 'publishedAt', direction: 'desc'}]},
  ],
})
